### ISSUE TITLE
restcountries.eu which is a source of information is not supported anymore

### ISSUE THREAD

**Issue by spryffee** [davidesantangelo/restcountry#5]
restcountries.eu is down and is not supported anymore. Maybe replacing it with restcountries.com could help, but looks like it doesn't support the flags.

**Comment by mansakondo** [comment]
> restcountries.eu is down and is not supported anymore. Maybe replacing it with restcountries.com could help, but looks like it doesn't support the flags.

@spryffee It seems that flags are supported in [version 3.1](https://restcountries.com/#api-endpoints-v3): 
https://restcountries.com/v3.1/all?fields=flag
https://restcountries.com/v3.1/all?fields=flags

But it seems that we can't combine filters like before so we might need to use instead https://restcountries.com/v3.1/all instead.
